[versions]
agp = "8.10.0"
android-compileSdk = "35"
android-minSdk = "26"
android-targetSdk = "35"
androidUikit = "v2.0.0"
androidx-activityCompose = "1.10.1"
androidx-lifecycle = "2.8.4"
assertk = "0.28.1"
coil = "3.1.0"
compose = "1.8.0"
composeIcons = "1.1.1"
composeTest = "1.8.1"
composeWebviewMultiplatform = "1.9.40"
compottie = "2.0.0-rc02"
coreKtx = "1.6.1"
coreSplashscreen = "1.0.1"
cryptographyBom = "0.4.0"
datastore = "1.1.6"
filekit = "0.10.0-beta04"
fullSdk = "4.5.2"
haze = "1.5.2"
hotReload = "1.0.0-alpha09"
koin = "4.0.3"
kotlin = "2.1.20"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.6.2"
kotlinx-serialization = "1.8.1"
ksp = "2.1.20-1.0.32"
ktor = "3.1.3"
logbackClassic = "1.5.16"
mediaPlayerKMP = "2.0.9"
navigationCompose = "2.8.0-alpha13"
osdetector = "1.7.3"
room = "2.7.1"
rootbeerLib = "0.1.1"
slf4jApi = "2.0.17"
sqlite = "2.5.1"
supabase = "3.1.4"
webkit = "1.13.0"

[libraries]
alert-kmp = { module = "io.github.khubaibkhan4:mediaplayer-kmp", version.ref = "mediaPlayerKMP" }
agora-uikit = { module = "com.github.AgoraIO-Community:Android-UIKit", version.ref = "androidUikit" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
coil-compose-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-core = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }
compose-ui-test-junit4-android = { module = "androidx.compose.ui:ui-test-junit4-android", version.ref = "composeTest" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeTest" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatform" }
composeIcons-evaIcons = { module = "br.com.devsrsouza.compose.icons:eva-icons", version.ref = "composeIcons" }
composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }
composeIcons-simpleIcons = { module = "br.com.devsrsouza.compose.icons:simple-icons", version.ref = "composeIcons" }
composeIcons-tablerIcons = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "composeIcons" }
compottie = { module = "io.github.alexzhirkevich:compottie", version.ref = "compottie" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtx" }
cryptography-bom = { module = "dev.whyoleg.cryptography:cryptography-bom", version.ref = "cryptographyBom" }
cryptography-core = { module = "dev.whyoleg.cryptography:cryptography-core" }
cryptography-provider-apple = { module = "dev.whyoleg.cryptography:cryptography-provider-apple" }
cryptography-provider-jdk = { module = "dev.whyoleg.cryptography:cryptography-provider-jdk" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogscompose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
agora-full-sdk = { module = "io.agora.rtc:full-sdk", version.ref = "fullSdk" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "haze" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-core-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
rootbeer-lib = { module = "com.scottyab:rootbeer-lib", version.ref = "rootbeerLib" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase" }
supabase-postgres = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabase-realtime = { module = "io.github.jan-tennert.supabase:realtime-kt" }
supabase-storage = { module = "io.github.jan-tennert.supabase:storage-kt" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrainsCompose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
room = { id = "androidx.room", version.ref = "room" }